// Sitedeki tüm sabit arayüz metinleri (içerik verisi değil, düğme/etiket/hata metinleri).
// İngilizce karşılığı: content/en/ui.ts — ikisi de aynı şekli taşımalı.

export const ui = {
  langSwitch: { label: "Dil", tr: "TR", en: "EN" },
  nav: { sectionsLabel: "Bölümler", contact: "İletişime geç", menuOpen: "Menüyü aç", chatCta: "Begüm'e sor", contactLabel: "İletişim" },
  cv: { button: "CV indir", tr: "Türkçe", en: "İngilizce", pdf: "PDF", mobileTr: "CV indir (Türkçe)", mobileEn: "CV indir (İngilizce)" },
  hero: {
    hello: "Merhaba, ben Begüm",
    ctaProjects: "Projelerimi gör",
    ctaContact: "Birlikte çalışalım",
    askPlaceholder: "Bana bir şey sor, cevaplayayım…",
    askLabel: "Begüm'e bir soru sor",
    scrollDown: "Aşağı kaydır",
    chips: [
      ["Kimsin?", "Kendinden kısaca bahseder misin?"],
      ["Projeler", "Hangi projeleri geliştirdin?"],
      ["Web sitesi yapıyor musun?", "Web sitesi de yapıyor musun?"],
    ] as [string, string][],
  },
  about: {
    eyebrow: "Hakkımda",
    openToWork: "Yeni fırsatlara açık",
    portraitAlt: "Begüm Alakuş, beyaz gömlek ve siyah ceketle",
    codeElse: "Kod dışında",
    countLabels: { projects: "öne çıkan proje", internships: "staj deneyimi", community: "topluluk & gönüllülük deneyimi", skills: "teknoloji ve beceri" },
    paragraphs: [
      "Bilgisayar Mühendisliği mezunuyum. React Native ile kullanıcı tarafında sade ve akıcı arayüzler, arka planda ise stabil ve güvenilir servisler kuruyorum. Geliştirme sürecimde güncel AI araçlarını mimariyi hızlandırmak ve edge-case'leri yakalamak için aktif birer çalışma arkadaşı gibi kullanıyorum.",
      "Bilgisayar başından kalktığımda beni genelde koşuda veya sporda bulabilirsiniz; kod tabanında aradığım o dinamizmi ve disiplini günün her anına yaymayı seviyorum.",
    ] as [string, string],
  },
  projects: { eyebrow: "Seçilmiş işler", lead: "Kaydırdıkça yandaki telefon projeden projeye geçer.", detail: "Detayları gör" },
  projectDialog: { label: "Proje detayı", close: "Kapat", whatIDid: "Ne yaptım", tech: "Teknolojiler", repo: "GitHub'da incele ↗" },
  experience: { eyebrow: "Künye", volunteering: "Gönüllülük" },
  events: {
    eyebrow: "Kampüste ve toplulukta",
    lead: "Üniversite boyunca topluluklarda aktif rol aldım: etkinlik düzenledim, sponsorluk yürüttüm, atölyelerde anlattım.",
    dragHint: "Etkinlik fotoğrafları, sürükleyerek kaydırabilirsin",
    prev: "Önceki fotoğraflar",
    next: "Sonraki fotoğraflar",
  },
  skills: { eyebrow: "Yetenekler", heading: "Kullandığım teknolojiler ve nerede kullandığım", hint: "Bir teknolojinin üzerine gel, nerede kullandığımı gör." },
  services: { eyebrow: "Uzmanlık Alanları", lead: "Ölçeklenebilir, performans odaklı mobil, web ve yapay zekâ destekli yazılım sistemleri geliştiriyorum." },
  contact: {
    eyebrow: "İletişim",
    lead: "İş fırsatı, bir web sitesi ya da mobil uygulama fikri… Formu doldur, mesajın doğrudan e-postama gelsin. Genelde 1–2 gün içinde dönüyorum.",
    linkedin: "LinkedIn ↗",
    github: "GitHub ↗",
  },
  copyEmail: { copy: "Kopyala", copied: "Kopyalandı", manual: "Seç + Ctrl+C" },
  form: {
    topicsLegend: "Ne hakkında?",
    topics: { job: "İş fırsatı", website: "Web sitesi", mobile: "Mobil uygulama", other: "Diğer" },
    nameLabel: "Adın", namePlaceholder: "Adın soyadın",
    emailLabel: "E-postan", emailPlaceholder: "ornek@mail.com",
    messageLabel: "Mesajın", messagePlaceholder: "Kısaca anlat, gerisini konuşuruz.",
    websiteLabel: "Web siten",
    submit: "Mesajı gönder",
    sending: "Gönderiliyor…",
    success: "Mesajın ulaştı, teşekkürler! En kısa sürede e-postana döneceğim.",
    failSuffix: "Olmazsa soldaki e-posta adresinden yazabilirsin.",
  },
  validation: {
    nameRequired: "Adını yazar mısın?",
    nameTooLong: "Ad en fazla 80 karakter olabilir.",
    emailInvalid: "Geçerli bir e-posta adresi yaz, sana buradan döneceğim.",
    messageTooShort: "Mesajın biraz kısa kaldı, birkaç cümleyle anlatır mısın?",
    messageTooLong: "Mesaj en fazla 2000 karakter olabilir.",
  },
  api: {
    rateLimited: "Kısa sürede çok fazla mesaj gönderildi. Biraz sonra tekrar dener misin?",
    invalidRequest: "Geçersiz istek.",
    formInvalid: "Formda eksik ya da hatalı alan var.",
    notConfigured: "Form şu an yapılandırılmadı, mesajın iletilmedi.",
    sendFailed: "Mesaj gönderilemedi. Birazdan tekrar dener misin?",
  },
  footer: { designedBy: "Tasarım ve kod: Begüm" },
  chat: {
    fab: "Begüm'e sor",
    drawerLabel: "Begüm'e sor",
    subtitle: "Asistanım, benim yazdığım cevaplarla konuşur",
    close: "Kapat",
    inputPlaceholder: "Bir soru yaz…",
    inputLabel: "Sorunu yaz",
    send: "Gönder",
    opening: "Merhaba, ben Begüm. Projelerim, deneyimim ya da birlikte ne yapabileceğimiz hakkında bana dilediğini sorabilirsin.",
    quick: [
      ["Ben", "Kendinden kısaca bahseder misin?"],
      ["Projeler", "Hangi projeleri geliştirdin?"],
      ["Yetenekler", "Hangi teknolojilerle çalışıyorsun?"],
      ["Deneyim", "İş deneyimlerini anlatır mısın?"],
      ["İletişim", "Sana nasıl ulaşabilirim?"],
    ] as [string, string][],
    emailLabel: "E-posta",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
  },
  notFound: {
    eyebrow: "404 · Sayfa bulunamadı",
    titlePre: "Bu ekran henüz",
    titleBold: "yayında değil.",
    lead: "Aradığın sayfa taşınmış ya da hiç var olmamış olabilir.",
    cta: "Ana sayfaya dön",
  },
} as const;
