// English mirror of content/tr/ui.ts — keep both in sync (same shape, same keys).

export const ui = {
  langSwitch: { label: "Language", tr: "TR", en: "EN" },
  nav: { sectionsLabel: "Sections", contact: "Get in touch", menuOpen: "Open menu", chatCta: "Ask Begüm", contactLabel: "Contact" },
  cv: { button: "Download CV", tr: "Turkish", en: "English", pdf: "PDF", mobileTr: "Download CV (Turkish)", mobileEn: "Download CV (English)" },
  hero: {
    hello: "Hi, I'm Begüm",
    ctaProjects: "See my projects",
    ctaContact: "Let's work together",
    askPlaceholder: "Ask me anything, I'll answer…",
    askLabel: "Ask Begüm a question",
    scrollDown: "Scroll down",
    chips: [
      ["Who are you?", "Can you tell me a bit about yourself?"],
      ["Projects", "Which projects have you built?"],
      ["Do you build websites?", "Do you also build websites?"],
    ] as [string, string][],
  },
  about: {
    eyebrow: "About",
    openToWork: "Open to new opportunities",
    portraitAlt: "Begüm Alakuş, wearing a white shirt and black blazer",
    codeElse: "Outside of code",
    countLabels: { projects: "featured projects", internships: "internships", community: "community & volunteer roles", skills: "technologies & skills" },
    paragraphs: [
      "I'm a Computer Engineering graduate. With React Native, I build interfaces that feel simple and fluid on the user's side, backed by services that hold up under pressure. In my dev process, I treat today's AI tools as active work partners — speeding up architecture decisions and catching edge cases early.",
      "Step away from the screen and you'll usually find me running or at the gym; I like carrying that same dynamism and discipline from the codebase into the rest of the day.",
    ] as [string, string],
  },
  projects: { eyebrow: "Selected work", lead: "As you scroll, the phone next to it switches from project to project.", detail: "See details" },
  projectDialog: { label: "Project details", close: "Close", whatIDid: "What I did", tech: "Technologies", repo: "View on GitHub ↗" },
  experience: { eyebrow: "Track record", volunteering: "Volunteering" },
  events: {
    eyebrow: "On campus and in the community",
    lead: "I've stayed active in student communities throughout university: organizing events, running sponsorships, teaching workshops.",
    dragHint: "Event photos — drag to scroll through them",
    prev: "Previous photos",
    next: "Next photos",
  },
  skills: { eyebrow: "Skills", hint: "Hover a technology to see where I've used it." },
  services: { eyebrow: "Areas of Expertise", lead: "I build scalable, performance-minded mobile, web, and AI-powered software systems." },
  contact: {
    eyebrow: "Contact",
    lead: "A job opportunity, a website, or a mobile app idea… Fill out the form and your message lands straight in my inbox. I usually reply within 1–2 days.",
    linkedin: "LinkedIn ↗",
    github: "GitHub ↗",
  },
  copyEmail: { copy: "Copy", copied: "Copied", manual: "Select + Ctrl+C" },
  form: {
    topicsLegend: "What's this about?",
    topics: { job: "Job opportunity", website: "Website", mobile: "Mobile app", other: "Other" },
    nameLabel: "Your name", namePlaceholder: "Your full name",
    emailLabel: "Your email", emailPlaceholder: "you@example.com",
    messageLabel: "Your message", messagePlaceholder: "Give me the short version — we can go deeper from there.",
    websiteLabel: "Your website",
    submit: "Send message",
    sending: "Sending…",
    success: "Your message is in — thank you! I'll get back to you by email soon.",
    failSuffix: "If this keeps happening, email me directly at the address on the left.",
  },
  validation: {
    nameRequired: "Mind adding your name?",
    nameTooLong: "Name can be at most 80 characters.",
    emailInvalid: "Please enter a valid email address so I can get back to you.",
    messageTooShort: "That's a little short — could you say a bit more in a sentence or two?",
    messageTooLong: "Message can be at most 2000 characters.",
  },
  api: {
    rateLimited: "Too many messages sent in a short time. Please try again in a bit.",
    invalidRequest: "Invalid request.",
    formInvalid: "Some fields are missing or invalid.",
    notConfigured: "The form isn't set up yet, so your message wasn't sent.",
    sendFailed: "The message couldn't be sent. Please try again shortly.",
  },
  footer: { designedBy: "Designed and built by Begüm" },
  chat: {
    fab: "Ask Begüm",
    drawerLabel: "Ask Begüm",
    subtitle: "My assistant — it answers using what I've written",
    close: "Close",
    inputPlaceholder: "Type a question…",
    inputLabel: "Type your question",
    send: "Send",
    opening: "Hi, I'm Begüm. Ask me anything about my projects, my experience, or what we could build together.",
    quick: [
      ["Me", "Can you tell me a bit about yourself?"],
      ["Projects", "Which projects have you built?"],
      ["Skills", "What technologies do you work with?"],
      ["Experience", "Can you tell me about your work experience?"],
      ["Contact", "How can I reach you?"],
    ] as [string, string][],
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
  },
  notFound: {
    eyebrow: "404 · Page not found",
    titlePre: "This screen isn't",
    titleBold: "live yet.",
    lead: "The page you're looking for may have moved, or it never existed.",
    cta: "Back to home",
  },
} as const;
